////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 8.20Release
// Tag = $Name: AKW8_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public class GarminProduct {
   public static final int HRM1 = 1;
   public static final int AXH01 = 2; // AXH01 HRM chipset
   public static final int AXB01 = 3;
   public static final int AXB02 = 4;
   public static final int HRM2SS = 5;
   public static final int DSI_ALF02 = 6;
   public static final int HRM_RUN_SINGLE_BYTE_PRODUCT_ID = 8; // hrm_run model for HRM ANT+ messaging
   public static final int FR405 = 717; // Forerunner 405
   public static final int FR50 = 782; // Forerunner 50
   public static final int FR60 = 988; // Forerunner 60
   public static final int DSI_ALF01 = 1011;
   public static final int FR310XT = 1018; // Forerunner 310
   public static final int EDGE500 = 1036;
   public static final int FR110 = 1124; // Forerunner 110
   public static final int EDGE800 = 1169;
   public static final int CHIRP = 1253;
   public static final int EDGE200 = 1325;
   public static final int FR910XT = 1328;
   public static final int ALF04 = 1341;
   public static final int FR610 = 1345;
   public static final int FR70 = 1436;
   public static final int FR310XT_4T = 1446;
   public static final int AMX = 1461;
   public static final int FR10 = 1482;
   public static final int SWIM = 1499;
   public static final int FENIX = 1551;
   public static final int EDGE510 = 1561;
   public static final int EDGE810 = 1567;
   public static final int TEMPE = 1570;
   public static final int VIRB_ELITE = 1735;
   public static final int EDGE_TOURING = 1736;
   public static final int HRM_RUN = 1752;
   public static final int SDM4 = 10007; // SDM4 footpod
   public static final int TRAINING_CENTER = 20119;
   public static final int ANDROID_ANTPLUS_PLUGIN = 65532;
   public static final int CONNECT = 65534; // Garmin Connect website
   public static final int INVALID = Fit.UINT16_INVALID;








}
